{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    # how you’ve configured identity on AKS:
    usePodIdentity: "{{ .Values.azureKeyVault.usePodIdentity }}"
    useVMManagedIdentity: "{{ .Values.azureKeyVault.useVMManagedIdentity }}"
    userAssignedIdentityID: "{{ .Values.azureKeyVault.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.azureKeyVault.vaultName }}"
    tenantId: "{{ .Values.azureKeyVault.tenantId }}"
    objects: |
      array:
      {{- range .Values.azureKeyVault.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          objectVersion: {{ .objectVersion }}
      {{- end }}

  # define the Kubernetes Secret(s) that will be created from these objects
  secretObjects:
    - secretName: kv-secret
      type: Opaque
      data:
      {{- range .Values.azureKeyVault.objects }}
        - key: {{ .objectName }}
          objectName: {{ .objectName }}
      {{- end }}
{{- end }}

