image:
  repository: myacrtsg.azurecr.io/webapp
  tag: "20250520.28"
  pullPolicy: IfNotPresent

servicePort: 80

ingress:
  enabled: true
  host: myapp.local
  className: webapprouting.kubernetes.azure.com
  tlsSecret: mychart-tls

azureKeyVault:
  enabled: true
  vaultName: "mykeyvaultfortsg123"
  tenantId: "bf701585-56ca-47a3-aad5-ba3e8f3b2e6d"
  userAssignedIdentityID: "e376acec-ed72-4054-975c-ef5713dd8d9c"
  usePodIdentity: "false"
  useVMManagedIdentity: "true"
  objects:
    - objectName: SuperSecret       
      objectType: secret            
      objectVersion: ""             

